module.exports = {
    name: 'error',
    description: "Tests the catch exception",
    execute(message, args) {
        InvalidException
    }
}